// Code generated by "enumer -type=Mode2_control -yaml"; DO NOT EDIT

package main

import (
	"fmt"
)

const _Mode2_control_name = "internalexternal"

var _Mode2_control_index = [...]uint8{0, 8, 16}

func (i Mode2_control) String() string {
	if i < 0 || i >= Mode2_control(len(_Mode2_control_index)-1) {
		return fmt.Sprintf("Mode2_control(%d)", i)
	}
	return _Mode2_control_name[_Mode2_control_index[i]:_Mode2_control_index[i+1]]
}

var _Mode2_controlNameToValue_map = map[string]Mode2_control{
	_Mode2_control_name[0:8]:  0,
	_Mode2_control_name[8:16]: 1,
}

func Mode2_controlString(s string) (Mode2_control, error) {
	if val, ok := _Mode2_controlNameToValue_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Mode2_control values", s)
}

func (i Mode2_control) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

func (i *Mode2_control) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = Mode2_controlString(s)
	return err
}
